# Generated by Django 3.0.1 on 2020-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleone',
            name='blog',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
