# Generated by Django 3.0.1 on 2020-02-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleone',
            name='author',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
