# Generated by Django 3.0.1 on 2020-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_styleone_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleone',
            name='category',
            field=models.CharField(choices=[('T', 'Travel'), ('L', 'Lifestyle')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
