# Generated by Django 3.0.1 on 2020-02-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_styleone_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleone',
            name='category',
            field=models.CharField(choices=[('T', 'Travel'), ('L', 'Lifestyle'), ('P', 'Personal'), ('B', 'Brand'), ('C', 'Corporate'), ('F', 'Finance'), ('S', 'Sports'), ('B', 'Business'), ('F', 'Food'), ('C', 'Cars'), ('M', 'Music'), ('G', 'Games'), ('F', 'Fitness'), ('E', 'Entertainment'), ('F', 'Fashion'), ('P', 'Politics'), ('P', 'Pets')], max_length=50),
        ),
    ]
