# Generated by Django 3.0.1 on 2020-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20200212_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleone',
            name='category',
            field=models.CharField(choices=[('Tr', 'Travel'), ('Li', 'Lifestyle'), ('Pe', 'Personal'), ('Br', 'Brand'), ('Co', 'Corporate'), ('Fi', 'Finance'), ('Sp', 'Sports'), ('Bu', 'Business'), ('Fo', 'Food'), ('Ca', 'Cars'), ('Mu', 'Music'), ('Ga', 'Games'), ('Fi', 'Fitness'), ('En', 'Entertainment'), ('Fa', 'Fashion'), ('Po', 'Politics'), ('Pe', 'Pets')], default='Personal', max_length=15),
        ),
    ]
