# Generated by Django 3.0.1 on 2020-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20200212_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleone',
            name='category',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('LIFESTYLE', 'Lifestyle'), ('PERSONAL', 'Personal'), ('BRAND', 'Brand'), ('CORPORATE', 'Corporate'), ('FINANACE', 'Finance'), ('SPORTS', 'Sports'), ('BUSINESS', 'Business'), ('FOOD', 'Food'), ('CARS', 'Cars'), ('MUSIC', 'Music'), ('GAMES', 'Games'), ('FITNESS', 'Fitness'), ('ENTERTAINMENT', 'Entertainment'), ('FASHION', 'Fashion'), ('POLITICS', 'Politics'), ('PETS', 'Pets')], default='Personal', max_length=15),
        ),
    ]
