# Generated by Django 3.0.1 on 2020-02-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20200212_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleone',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Personal', 'Personal'), ('Brand', 'Brand'), ('Corporate', 'Corporate'), ('Finance', 'Finance'), ('Sports', 'Sports'), ('Business', 'Business'), ('Food', 'Food'), ('Cars', 'Cars'), ('Music', 'Music'), ('Games', 'Games'), ('Fitness', 'Fitness'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Politics', 'Politics'), ('Pets', 'Pets')], default='Personal', max_length=15),
        ),
    ]
