# Generated by Django 3.0.1 on 2020-02-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_styleone_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StyleTwo',
        ),
    ]
