# Generated by Django 3.0.1 on 2020-02-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user'),
        ('page', '0017_delete_styletwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AlterField(
            model_name='styleone',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AlterField(
            model_name='styleone',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='account.User'),
        ),
    ]
