# Generated by Django 3.0.1 on 2020-02-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20200220_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styleone',
            old_name='author',
            new_name='user_id',
        ),
    ]
