# Generated by Django 3.0.1 on 2020-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
