# Generated by Django 3.0.1 on 2020-02-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_category_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
