# Generated by Django 3.0.1 on 2020-02-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
